### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by oscarotero** [middlewares/redirect#1]
Thank you very much for your work. I'd like to drop here some suggestions that I think would improve this package. Let me know your opinion:

* The `$redirects` argument might be an array or an `ArrayAccess` object. This make the middleware more flexible, for example allowing to use a database with all urls and wrapping the connection in a `ArrayAccess` object. May be useful if you have a large amount of urls. This is something that I've planned to do in other middlewares like [http autentication](https://github.com/middlewares/http-authentication).
* I'm not sure the http code should be configured. The purpose of this middleware is rename old urls to new urls smoothly. This option, tecnically allows to use any http code, breaking the initial intention.
* There's a `use Zend\Diactoros\Response;` in the middleware that it's not used.
* What if the url have query parameters?
* What if the request is `POST`, `PUT` or any other similar method? Should return a `405` response or a `308`?

**Comment by WyriHaximus** [comment]
> The $redirects argument might be an array or an ArrayAccess object. This make the middleware more flexible, for example allowing to use a database with all urls and wrapping the connection in a ArrayAccess object. May be useful if you have a large amount of urls. This is something that I've planned to do in other middlewares like http autentication.

 Sure 👍 

> I'm not sure the http code should be configured. The purpose of this middleware is rename old urls to new urls smoothly. This option, tecnically allows to use any http code, breaking the initial intention.

IMHO any 3xx redirect code should be allowed for use (301, 302, 303, 307, and 308) so making it configurable lets you deal with all those possible use cases.

> There's a use Zend\Diactoros\Response; in the middleware that it's not used.

I'll remove it 👍 

> What if the url have query parameters?

Right now any query is ignore as they aren't part of the path. But could add bool to include it.

> What if the request is POST, PUT or any other similar method? Should return a 405 response or a 308?

What about making it a bool, 308 on allow and 405 on disallowed?

**Comment by oscarotero** [comment]
Ok, what do you thing about this?

```php
$redirect = (new Middlewares\Redirect($urls))
    ->permanent(false) //to use 302 responses, instead 301 which is used by default
    ->method(['GET', 'POST', 'PUT']) //To use just these methods and return a 405 response for others. POST and PUT will return 307 response because permanent is false, otherwise returns 308
```

Moving the options to methods leaves the constructor with just one argument, the only required value. This is something that I tend to do in the other middlewares.

I'd like to add also an option to include the query parameters, in order to allow redirections like `'/post.php?id=34' => '/post/34'`.

**Comment by WyriHaximus** [comment]
> Ok, what do you thing about this?
> 
> ```php
> $redirect = (new Middlewares\Redirect($urls))
>     ->permanent(false) //to use 302 responses, instead 301 which is used by default
>     ->method(['GET', 'POST', 'PUT']) //To use just these methods and return a 405 response for others. POST and PUT will return 307 response because permanent is false, otherwise returns 308
> ```
> 
> Moving the options to methods leaves the constructor with just one argument, the only required value. This is something that I tend to do in the other middlewares.

Perfect 👍 

> I'd like to add also an option to include the query parameters, in order to allow redirections like `'/post.php?id=34' => '/post/34'`.

Sure that would work

**Comment by oscarotero** [comment]
Great. Thank you for the good work.
There's some things to do yet (update readme, changelog, etc), but feel free to transfer this repo to the middlewares organization when you want.

**Comment by WyriHaximus** [comment]
Cheers, I'll update the readme etc before transfering it to the middlewares organization 👍

**Comment by WyriHaximus** [comment]
Alright transferred the repository, could you set up the CI's?

**Comment by oscarotero** [comment]
Done.

**Comment by WyriHaximus** [comment]
Awesome :tada:

**Comment by WyriHaximus** [comment]
Anything left to do before the first tag?

**Comment by oscarotero** [comment]
I miss the option for the query parameters.

Also, the http-interop/http-middleware interface [was updated to v0.5.0](https://github.com/http-interop/http-middleware/releases), so we can update this package too, but it requires to update [middlewares/utils](https://github.com/middlewares/utils) before. [I've commited the changes](https://github.com/middlewares/utils/commit/0258b9e257247ee18b8328884b0ce401cf1575a9), tomorrow will tag the new release.

**Comment by WyriHaximus** [comment]
I'll file a PR for that tomorrow, also IMHO would prefer seeing a version for 0.4 and 0.5 of `http-interop/http-middleware` so users have the time to move to the new `http-interop/http-middleware`.

**Comment by oscarotero** [comment]
Fair enough.

**Comment by WyriHaximus** [comment]
Filed #2 for the query option

**Comment by oscarotero** [comment]
First version released, supporting http-interop/http-middleware v0.4

**Comment by WyriHaximus** [comment]
Awesome, I'll update my project :tada: !
