### ISSUE TITLE
Missing middlewares/utils

### ISSUE THREAD

**Issue by WyriHaximus** [middlewares/redirect#3]
An issue came up at https://github.com/friends-of-reactphp/http-middleware-psr15-adapter/issues/3 where when just installing `middlewares/redirect` throws an error because it is missing `middlewares/utils` by default. Is there a reason to keep `middlewares/utils` in `require-dev` instead of including it in `require?

**Comment by oscarotero** [comment]
No, there is no reason, its a bug.
I'm fixing this now.

**Comment by WyriHaximus** [comment]
Great :+1:

**Comment by oscarotero** [comment]
Done.

**Comment by WyriHaximus** [comment]
Thanks :tada:
